version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ceerion-mail-postgres
    environment:
      POSTGRES_DB: ceerion_mail
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ceerion-mail-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ceerion-mail-redis
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ceerion-mail-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  ceerion-mail-network:
    driver: bridge
