/**
 * Admin Library Index
 * Re-exports all admin-related types and APIs
 */

// Types
export type {
  DomainStatus,
  DnsRecordType,
  DnsRecordStatus,
  DkimKeyStatus,
  DkimAlgorithm,
  CatchAllAction,
  DnsRecord,
  DnsStatus,
  DkimKey,
  GenerateDkimKeyRequest,
  CatchAllConfig,
  SendingLimits,
  SecuritySettings,
  DomainSettings,
  DomainBranding,
  AdminDomain,
  AdminDomainDetail,
  DomainUser,
  ListDomainsQuery,
  ListDomainsResponse,
  CreateDomainRequest,
  VerificationMethod,
  VerificationRecord,
  VerifyDomainRequest,
  VerifyDomainResponse,
  ConfigureDnsResponse,
  UpdateDomainSettingsRequest,
  UpdateDomainBrandingRequest,
  ListDomainUsersQuery,
  ListDomainUsersResponse,
  BulkUserAction,
  AddDomainWizardStep,
  AddDomainWizardState,
  ExportDomainsRequest,
} from "./types";

// API Hooks
export {
  domainAdminKeys,
  useDomainsList,
  useDomainDetail,
  useCreateDomain,
  useCheckDomainAvailability,
  useVerificationRecord,
  useVerifyDomain,
  useUpdateDomainStatus,
  useMakeDomainPrimary,
  useDeleteDomain,
  useDnsRecords,
  useVerifyDns,
  useBulkVerifyDns,
  useDkimKeys,
  useGenerateDkimKey,
  useUpdateDkimKeyStatus,
  useDeleteDkimKey,
  useDomainSettings,
  useUpdateDomainSettings,
  useDomainBranding,
  useUpdateDomainBranding,
  useUploadBrandingAsset,
  useDomainUsers,
  useAddUserToDomain,
  useBulkUserAction,
  useExportDomains,
} from "./domain-admin-api";
