#!/bin/bash

# CEERION Mail DNS Records Verification Script

echo "=============================================="
echo "CEERION MAIL DNS RECORDS - READY TO PUBLISH"
echo "=============================================="
echo ""

echo "1. A RECORD:"
echo "   Name: mail.ceerion.com"
echo "   Type: A"
echo "   Value: 209.126.9.62"
echo "   TTL: 3600"
echo ""

echo "2. MX RECORD:"
echo "   Name: ceerion.com (or @)"
echo "   Type: MX" 
echo "   Value: mail.ceerion.com"
echo "   Priority: 10"
echo "   TTL: 3600"
echo ""

echo "3. SPF RECORD:"
echo "   Name: ceerion.com (or @)"
echo "   Type: TXT"
echo "   Value: v=spf1 mx -all"
echo "   TTL: 3600"
echo ""

echo "4. DKIM RECORD:"
echo "   Name: ceerion._domainkey.ceerion.com"
echo "   Type: TXT"
echo "   Value: v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu8VLMI9m8OMe/qGdt3xIhUx9RcwYGhpbhlNC8gFYf92fMhvq0aubCeo7/ACHElY5Ilbvkh0ybz0sTN4rBd51yXFdR+K4AzqzBuNXM8Z4E0xHhhpeTXO7xHfxYSPa1MDPvw0Nblan9QqVBLjz9sk6Xf9Jhg0vTGzfX+goaZmk1NyXIJky0E83+2DNE4qZtnkSR8tjCG5+y2tJdlDzPpijE476ztvUDc9Wunxmb0ibhTn1S/cQxBerNRxk8seeTbUD9UFXqP3tZXqsjw5ndJ5e5xRUcxcXcU1f77ni9DPdLE3kIj8LeXfPSUAc3isN5G/6KIafo5x7mum0bZednRgNvQIDAQAB"
echo "   TTL: 3600"
echo ""

echo "5. DMARC RECORD:"
echo "   Name: _dmarc.ceerion.com"
echo "   Type: TXT"
echo "   Value: v=DMARC1; p=quarantine; rua=mailto:dmarc@ceerion.com; ruf=mailto:dmarc@ceerion.com; fo=1"
echo "   TTL: 3600"
echo ""

echo "6. MTA-STS RECORD:"
echo "   Name: _mta-sts.ceerion.com"
echo "   Type: TXT"
echo "   Value: v=STSv1; id=20250828"
echo "   TTL: 3600"
echo ""

echo "7. TLS-RPT RECORD:"
echo "   Name: _smtp._tls.ceerion.com"
echo "   Type: TXT"
echo "   Value: v=TLSRPTv1; rua=mailto:tlsrpt@ceerion.com"
echo "   TTL: 3600"
echo ""

echo "8. PTR RECORD (Contact hosting provider):"
echo "   IP: 209.126.9.62"
echo "   Value: mail.ceerion.com"
echo ""

echo "=============================================="
echo "VERIFICATION COMMANDS:"
echo "=============================================="
echo ""
echo "dig MX ceerion.com +short"
echo "dig A mail.ceerion.com +short"
echo "dig TXT ceerion.com | grep spf"
echo "dig TXT ceerion._domainkey.ceerion.com"
echo "dig TXT _dmarc.ceerion.com"
echo "dig TXT _mta-sts.ceerion.com"
echo "dig TXT _smtp._tls.ceerion.com"
echo ""

echo "=============================================="
echo "REQUIRED EMAIL ADDRESSES:"
echo "=============================================="
echo "- postmaster@ceerion.com"
echo "- abuse@ceerion.com"
echo "- dmarc@ceerion.com"
echo "- tlsrpt@ceerion.com"
echo ""

echo "=============================================="
echo "STATUS: READY FOR DNS PUBLICATION ✅"
echo "=============================================="
